### PR TITLE
Applied formatting script and created CI workflow to check formatting.

### PR DESCRIPTION
**Pull request by bwvdnbro**
Implements the first part of #3.

### CODE REVIEW

**Comment by bwvdnbro** [comment]
Seems to work. It's nice when a PR tests itself.

**Comment by MatthieuSchaller** [comment]
> Seems to work. It's nice when a PR tests itself.

That's dangerously close to the singularity...

**Review by MatthieuSchaller — APPROVED** [review]
All worked and the changes are all at the formatting level so happy to accept.

Are more changed expected in this same PR already?

**Comment by bwvdnbro** [comment]
No, this should be merged now to avoid too many conflicts.

**Pull request merged**
